import React from 'react'
import PropTypes from 'prop-types'

export const metadata = {
    title: 'codebystupid about',
    description: 'Generated by create next app',
  }

function About(props) {
  return (
    <div>This is a about page</div>
  )
}

About.propTypes = {}

export default About
