import React from 'react'

export const metadata = {
    title: 'codebystupid team about',
    description: 'Generated by create next app',
  }

const Team = () => {
  return (
    <div>This is a team Component</div>
  )
}

export default Team
